### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by svenstaro** [dagwieers/dstat#55] opened 2013-09-29 16:31 UTC
Currently distros are still using the version 0.7.2 from 2012. I think a new release should be considered.

**Comment by svenstaro** [comment] 2015-05-05 13:56
@dagwieers can you give us a life sign?

**Comment by scottchiefbaker** [comment] 2015-06-08 17:17
@dagwieers have you abandoned this project? Would we be better suited forking the code and finding a new maintainer? The last git commit was almost a year ago.

**Comment by dagwieers** [comment] 2015-06-08 17:43
Why fork ? If someone wants to do the release management, why not offer to
do it ?

**Comment by scottchiefbaker** [comment] 2015-06-08 17:46
What's involved in doing the release management?

I only suggested forking the code because it seems like you don't have much interest any more. Mainly based on the git commit history.

**Comment by SpamapS** [comment] 2015-10-06 18:06
@dagwieers I think @scottchiefbaker *was* actually offering to do the release. :)

**Comment by SpamapS** [comment] 2015-10-06 18:08
Just a point of interest here. I am working on using dstat to improve performance metrics in OpenStack. The dstat_mysql5_innodb plugin would be perfect for this, but has not been released so access to it is limited to git cloners. Please do a release, and if there is anything I can do to help (including setting up a group on Github, forking this repo, and releasing from that repo) I'm quite motivated to get this out there and into distros ASAP. Thanks!

**Comment by SpamapS** [comment] 2015-10-12 20:05
Dag, hopefully you're reading your email. Can you check your spam folder for email from clint@fewbar.com (Thats me). I sent you an offer to help, and have received no response.

**Comment by kdave** [comment] 2015-10-16 12:39
If I may suggest something: give it a month and if you don't get any response or the release happens:

* start a dstat-ng fork
* tag the release in current git with some 'rc' so there's time for fixups before the final release
* write changelog: ie. a high-level overview of new functionality, important fixes
* do teh release

At this point you'll make a lot of people happy, dstat is just too awesome to be ignored like it is.

Then:

* go on and review & merge the outstanding pull requests, the easy ones first
* tag another release minor after some weeks (a month schedule would be fine until the pull request queue goes down)

The "-ng" approach worked for several projects. If the git continuity is not broken, a back merge to the original project can happen at some point.

**Comment by scottchiefbaker** [comment] 2016-03-14 03:24
This is my annual request for a new dstat release :)

**Comment by dagwieers** [comment] 2016-03-14 08:57
Whoops, @SpamapS I did not see your mail, so it must have gone to the SPAM folder.

@kdave Indeed, that's basically what is needed for doing a release. Except you also want to look at the PRs and issue tickets to see what's important and still needs to be addressed. Usually I keep track of loose-ends using the GitHub Milestones.

The problem is that even if you spend some time doing the above (which I did a few times over the years) and then get stalled (keeping up with real life) you may have to start over again. Ad inifinitum...

**Comment by dagwieers** [comment] 2016-03-14 09:06
@SpamapS You are now a collaborator. Whatever that entails :-)

I don't mind making Dstat a Github project, open up the discussions about the future of Dstat, give more people rights to manage the project, etc.

**Comment by scottchiefbaker** [comment] 2016-03-14 15:03
@dagwieers I think making dstat a community Github project is a great idea. There are obviously quite a few people passionate about the project. I'm happy to help in any way possible. I literally use dstat everyday, so I look forward to seeing it thrive.

**Comment by thinrope** [comment] 2016-03-15 01:15
Well, heart is on, @SpamapS, we are looking at you now!

**Comment by dagwieers** [comment] 2016-03-15 11:31
@scottchiefbaker You made your case. You are now a contributor too :-)

**Comment by dagwieers** [comment] 2016-03-15 12:54
Ok, I wanted to create a new @dstat project on Github, but the account is already taken :-/
So we cannot have dstat/dstat. Not sure what else we would want to do.

**Comment by svenstaro** [comment] 2016-03-15 13:02
Write Github support to request dstat/dstat. That account has not been used for 2 years it would appear. This is an ok-thing to do, I did it once.

**Comment by dagwieers** [comment] 2016-03-15 13:05
I already did, they say user @dstat is not dormant even though there is no public activity. So we are out of luck. We could rename the project.

Originally I started using the name mstat (modular statistics), but that conflicted with some other project). I selected dstat because with only 2 characters (ds) you could get to the command, and on my system today that is still the case.

**Comment by scottchiefbaker** [comment] 2016-03-15 15:24
@dagwieers Yay! Glad to be part of the team. Long live dstat.

If we can't have dstat / dstat maybe we can create a new group, but keep the dstat name? Something like: wieersware / dstat or something? I like the name dstat, I don't think that needs to change just because someone else has that group on github.

**Comment by scottchiefbaker** [comment] 2016-03-15 15:31
@svenstaro is there a way to reach out to @dstat and see if they're actively using that account?

**Comment by dagwieers** [comment] 2016-03-15 15:32
@scottchiefbaker Only through Github support (which I did) or through comments like these to @dstat :-)

**Comment by scottchiefbaker** [comment] 2016-03-15 15:37
@dagwieers ah ok... We can cross that bridge a bit later if we can agree on a good organization name. I think step #1 is going to be to establish a plan for the next release. If you don't mind I'd like to close this issue (or you can), and start a new one with less old cruft.

**Comment by dagwieers** [comment] 2016-03-15 15:42
Go ahead. I gave away all my rights to block this thing years ago.

**Closed by dagwieers** 2016-03-15 15:42 UTC
Labels: feature
